PROG=../../../bin/Codecs/AES.dll

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)

OBJS = \
../../../BUILD/Common/MyWindows.o \
DllExports.o\
MyAES.o\
aescrypt.o\
aeskey.o\
aestab.o

include ../../../makefile.glb

