PROG=../../../bin/Codecs/AES.dll

LOCAL_FLAGS=

MY_WINDOWS= $(MY_HOME)/wine_variant.o $(MY_HOME)/wine_BSTR.o

LOCAL_SHARED=-shared

OBJS = \
	DllExports.o \
	InBuffer.o \
	OutBuffer.o \
	aescrypt.o \
	aestab.o \
	aeskey.o \
	MyAES.o

include ../../../makefile.glb

