PROG=../../../bin/Codecs/Copy.dll

LOCAL_FLAGS=

MY_WINDOWS= $(MY_HOME)/wine_variant.o $(MY_HOME)/wine_BSTR.o

LOCAL_SHARED=-shared

OBJS = \
	DllExports.o \
	CopyCoder.o

include ../../../makefile.glb

