PROG=../../../bin/Codecs/Copy.dll

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)

OBJS = \
../../../BUILD/Common/MyWindows.o \
DllExports.o \
../../../BUILD/Common/Alloc.o\
CopyCoder.o

include ../../../makefile.glb

