PROG=../../../bin/Codecs/Deflate.dll

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)

OBJS = \
../../../BUILD/Common/MyWindows.o \
../../../BUILD/Common/Alloc.o\
../../../BUILD/Common/CRC.o\
DllExports.o\
HuffmanEncoder.o\
InBuffer.o\
LSBFDecoder.o\
LSBFEncoder.o\
OutBuffer.o\
LZInWindow.o\
LZOutWindow.o\
DeflateDecoder.o\
DeflateEncoder.o

include ../../../makefile.glb

