
ALLFLAGS=-Wall -O2 -s \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT \
	$(LOCAL_FLAGS)

CXX=g++ $(ALLFLAGS)
CC=gcc $(ALLFLAGS)

#LOCAL_LIBS=-lpthread
# static linkage
LOCAL_LIBS=-static -lpthread

