
MY_HOME=../../../myWindows

LIBS=$(LOCAL_LIBS)
RM=rm -f
CFLAGS=-c \
-I../../../myWindows \
-I../../../ \
-I../../../include_windows

all:$(PROG)

$(PROG): $(OBJS) $(MY_WINDOWS)
	$(CXX) $(LOCAL_SHARED) -o $(PROG) $(LDFLAGS) $(OBJS) $(MY_WINDOWS) $(LIBS)

include makefile.list

clean:
	-@$(RM) $(PROG) $(PROG).exe *.o *~ 

