PROG=../../../bin/Formats/rpm.dll

LOCAL_FLAGS=

LOCAL_SHARED=-shared

MY_WINDOWS=$(MY_HOME)/wine_variant.o $(MY_HOME)/wine_BSTR.o

OBJS = \
	DllExports.o \
	PropVariant.o \
	ProgressUtils.o \
	CopyCoder.o \
	RpmHandler.o \
	RpmIn.o \

include ../../../makefile.glb

