PROG=../../../bin/Formats/rpm.dll

LOCAL_FLAGS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)

MY_WINDOWS=

OBJS = \
../../../BUILD/Common/MyWindows.o \
DllExports.o\
PropVariant.o\
ProgressUtils.o\
CopyCoder.o\
../../../BUILD/Common/Alloc.o\
RpmHandler.o\
RpmIn.o

include ../../../makefile.glb

