PROG=../../../bin/Codecs/Implode.dll

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)

OBJS = \
../../../BUILD/Common/MyWindows.o \
../../../BUILD/Common/Alloc.o\
DllExports.o\
InBuffer.o\
LSBFDecoder.o\
LZOutWindow.o\
ImplodeDecoder.o\
ImplodeHuffmanDecoder.o

include ../../../makefile.glb

