PROG=../../../bin/Codecs/Implode.dll

LOCAL_FLAGS=

MY_WINDOWS= $(MY_HOME)/wine_variant.o $(MY_HOME)/wine_BSTR.o

LOCAL_SHARED=-shared

OBJS = \
	DllExports.o \
	InBuffer.o \
	LSBFDecoder.o \
	LZOutWindow.o \
	ImplodeDecoder.o \
	ImplodeHuffmanDecoder.o

include ../../../makefile.glb

