PROG=../../../bin/Codecs/Branch.dll

LOCAL_FLAGS=

MY_WINDOWS= $(MY_HOME)/wine_variant.o $(MY_HOME)/wine_BSTR.o

LOCAL_SHARED=-shared

OBJS = \
	DllExports.o \
	Alpha.o \
	ARM.o \
	ARMThumb.o \
	IA64.o \
	M68.o \
	PPC.o \
	x86.o \
	x86_2.o \
	InBuffer.o \
	OutBuffer.o

include ../../../makefile.glb

