#ifndef _WINERROR_H
#define _WINERROR_H

#define NO_ERROR                     0L
#define ERROR_FILE_NOT_FOUND         2L
#define ERROR_PATH_NOT_FOUND         3L
#define ERROR_ACCESS_DENIED          5L
#define ERROR_INVALID_HANDLE         6L
#define ERROR_BAD_FORMAT            11L
#define ERROR_NO_MORE_FILES         18L
#define ERROR_SEEK                  25L
#define ERROR_GEN_FAILURE           31L
#define ERROR_SHARING_VIOLATION     32L
#define ERROR_LOCK_VIOLATION        33L
#define ERROR_HANDLE_DISK_FULL      39L
#define ERROR_FILE_EXISTS           80L
#define ERROR_CANNOT_MAKE           82L
#define ERROR_INVALID_PARAMETER     87L
#define ERROR_BROKEN_PIPE          109L
#define ERROR_DISK_FULL            112L
#define ERROR_CALL_NOT_IMPLEMENTED 120L
#define ERROR_DIR_NOT_EMPTY        145L
#define ERROR_ALREADY_EXISTS       183L
#define ERROR_FILENAME_EXCED_RANGE 206L

#define S_OK ((HRESULT)0x00000000L)
#define S_FALSE ((HRESULT)0x00000001L)
#define E_INVALIDARG ((HRESULT)0x80070057L)
#define E_NOTIMPL ((HRESULT)0x80004001L)
#define E_NOINTERFACE ((HRESULT)0x80004002L)
#define E_ABORT ((HRESULT)0x80004004L)
#define E_FAIL ((HRESULT)0x80004005L)
#define E_OUTOFMEMORY ((HRESULT)0x8007000EL)

#define STG_E_INVALIDFUNCTION ((HRESULT)0x80030001L)

#define SUCCEEDED(Status) ((HRESULT)(Status) >= 0)
#define FAILED(Status) ((HRESULT)(Status)<0)

#endif
