myDirectoryAndPath.o : myDirectoryAndPath.cpp
	$(CXX) $(CFLAGS) myDirectoryAndPath.cpp

mySplitCommandLine.o : mySplitCommandLine.cpp
	$(CXX) $(CFLAGS) mySplitCommandLine.cpp

myEvents.o : myEvents.cpp
	$(CXX) $(CFLAGS) myEvents.cpp

myFiles.o : myFiles.cpp
	$(CXX) $(CFLAGS) myFiles.cpp

myFindFile.o : myFindFile.cpp
	$(CXX) $(CFLAGS) myFindFile.cpp

myLastError.o : myLastError.cpp
	$(CXX) $(CFLAGS) myLastError.cpp

myModuleFileName.o : myModuleFileName.cpp
	$(CXX) $(CFLAGS) myModuleFileName.cpp

myGetTickCount.o : myGetTickCount.cpp
	$(CXX) $(CFLAGS) myGetTickCount.cpp

test_emul.o : test_emul.cpp
	$(CXX) $(CFLAGS) test_emul.cpp

wine_date_and_time.o : wine_date_and_time.cpp
	$(CXX) $(CFLAGS) wine_date_and_time.cpp

wine_strings.o : wine_strings.cpp
	$(CXX) $(CFLAGS) wine_strings.cpp

Vector.o : ../Common/Vector.cpp
	$(CXX) $(CFLAGS) ../Common/Vector.cpp

MyWindows.o : ../Common/MyWindows.cpp
	$(CXX) $(CFLAGS) ../Common/MyWindows.cpp

