PROG=all.so

LOCAL_FLAGS=-I. -I.. -I../include_windows

include ../makefile.machine

OBJS=myEvents.o myFiles.o myFindFile.o myDirectoryAndPath.o \
	myLastError.o myModuleFileName.o my_itow.o \
	wine_wsprintf.o wine_date_and_time.o wine_BSTR.o wine_variant.o wine_strings.o \
	test_emul.o \
	stuff_for_cygwin.o

include ../makefile.glb

