PROG=../../../bin/7z

LOCAL_FLAGS=

include ../../../makefile.machine

MY_WINDOWS=$(MY_HOME)/myDirectoryAndPath.o \
	$(MY_HOME)/myLastError.o \
	$(MY_HOME)/myEvents.o \
	$(MY_HOME)/myFiles.o \
	$(MY_HOME)/myFindFile.o \
	$(MY_HOME)/myModuleFileName.o \
	$(MY_HOME)/wine_date_and_time.o \
	$(MY_HOME)/wine_strings.o

OBJS = \
../../../BUILD/Common/MyWindows.o \
../../../BUILD/Common/Alloc.o \
../../../BUILD/Common/CommandLineParser.o \
../../../BUILD/Common/StdInStream.o \
../../../BUILD/Common/StdOutStream.o \
../../../BUILD/Common/ListFileUtils.o \
../../../BUILD/Common/UTFConvert.o \
../../../BUILD/Common/Vector.o \
../../../BUILD/Common/Wildcard.o \
../../../BUILD/Common/StringConvert.o \
../../../BUILD/Common/String.o \
../../../BUILD/Common/IntToString.o \
../../../BUILD/Common/StringToInt.o \
ConsoleClose.o \
ExtractCallbackConsole.o \
List.o \
Main.o \
MainAr.o \
OpenCallbackConsole.o \
PercentPrinter.o \
UpdateCallbackConsole.o \
UserInputUtils.o \
DLL.o \
Error.o \
FileDir.o \
FileFind.o \
FileIO.o \
FileName.o \
PropVariant.o \
PropVariantConversions.o \
ArchiveCommandLine.o \
ArchiveExtractCallback.o \
ArchiveOpenCallback.o \
DefaultName.o \
EnumDirItems.o \
Extract.o \
ExtractingFilePath.o \
ArchiverInfo.o \
OpenArchive.o \
PropIDUtils.o \
SortUtils.o \
TempFiles.o \
Update.o \
UpdateAction.o \
UpdateCallback.o \
UpdatePair.o \
UpdateProduce.o \
FilePathAutoRename.o \
FileStreams.o \
CopyCoder.o

include ../../../makefile.glb

