PROG=../../../bin/Codecs/Swap.dll

LOCAL_FLAGS=

MY_WINDOWS= $(MY_HOME)/wine_BSTR.o  $(MY_HOME)/wine_variant.o 

LOCAL_SHARED=-shared

OBJS = \
	DllExports.o \
	ByteSwap.o

include ../../../makefile.glb

