SRCS=myGetTickCount.cpp \
 mySplitCommandLine.cpp \
 myAddExeFlag.cpp \
 test_emul.cpp \
 wine_date_and_time.cpp

mySplitCommandLine.o : mySplitCommandLine.cpp
	$(CXX) $(CFLAGS) mySplitCommandLine.cpp
myAddExeFlag.o : myAddExeFlag.cpp
	$(CXX) $(CFLAGS) myAddExeFlag.cpp
myGetTickCount.o : myGetTickCount.cpp
	$(CXX) $(CFLAGS) myGetTickCount.cpp
test_emul.o : test_emul.cpp
	$(CXX) $(CFLAGS) test_emul.cpp
wine_date_and_time.o : wine_date_and_time.cpp
	$(CXX) $(CFLAGS) wine_date_and_time.cpp
