PROG=../../../bin/Codecs/PPMD.dll

LOCAL_FLAGS=

MY_WINDOWS= $(MY_HOME)/wine_variant.o $(MY_HOME)/wine_BSTR.o

LOCAL_SHARED=-shared

OBJS = \
	DllExports.o \
	PPMDDecoder.o \
	PPMDEncoder.o \
	InBuffer.o \
	OutBuffer.o

include ../../../makefile.glb

