PROG=../../../bin/Codecs/PPMD.dll

LOCAL_FLAGS=

MY_WINDOWS=

include ../../../makefile.machine

LOCAL_SHARED=$(LINK_SHARED)

OBJS = \
../../../BUILD/Common/MyWindows.o \
../../../BUILD/Common/Alloc.o \
DllExports.o\
PPMDDecoder.o\
PPMDEncoder.o\
InBuffer.o\
OutBuffer.o

include ../../../makefile.glb

